### ISSUE TITLE
Create a Template for People to Submitt Community Submission requests

### ISSUE THREAD

**Issue by anajsana** [chaoss/oscdb#8]
Idea to create a GitHub issue template that allows folks to easily submit their community details using a clear and structured format. This will help collect consistent information about different community groups that want to be listed. We can also make use of GitHub actions to trigger an automated message when an issue is created to mention that the group will review and get back to them when ready (depending on the review / selection process)

### Steps

1. Create a new issue template file in https://github.com/chaoss/oscdb/.github/ISSUE_TEMPLATE/community-submission.yml

2. Add the following YAML content to the file:

```yml
name: Community Submission
description: Submit your community to be included in our listings or initiatives
title: "[Community Submission] <Community Name>"
labels: ["community", "submission"]
body:
  - type: markdown
    attributes:
      value: |
        🙌 Thank you for submitting your community! Please complete the form below with the required information
  - type: input
    id: community-name
    attributes:
      label: Community Name
      placeholder: e.g Awesome Dev and Country Name
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the purpose or focus of your community.
      placeholder: e.g A group of developers meeting monthly to discuss cloud-native
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website or Link
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: Region
      placeholder: e.g China, India, Japan
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Community Category
      options:
        - Developer Group
        - Meetup
        - Chapter
        - Other
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Format
      options:
        - In-person
        - Virtual
        - Hybrid
    validations:
      required: true
```

### Assignee

Ana (myself) can create a PR if the community likes the idea 🙂
